/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empmanagement.gui;

import empmanagement.dao.empDAO;
import empmanagement.dbutil.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class DeleteEmployeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeleteEmployeeFrame
     */
    public DeleteEmployeeFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Delete Employee");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteEmployeePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDeleteEmpNo = new javax.swing.JTextField();
        btnDeleteEmp = new javax.swing.JButton();
        btnDeleteEmpBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtViewDetails = new javax.swing.JTextArea();
        btnViewAllEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("<html>\n<body>\n<h3>Delete Employee</h3>\n</body>\n</html>");

        deleteEmployeePanel.setBackground(new java.awt.Color(0, 0, 0));
        deleteEmployeePanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Employee");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Emp No      ");

        txtDeleteEmpNo.setForeground(new java.awt.Color(255, 255, 255));
        txtDeleteEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteEmpNoActionPerformed(evt);
            }
        });

        btnDeleteEmp.setText("Delete");
        btnDeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmpActionPerformed(evt);
            }
        });

        btnDeleteEmpBack.setText("Back");
        btnDeleteEmpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmpBackActionPerformed(evt);
            }
        });

        txtViewDetails.setBackground(new java.awt.Color(0, 0, 0));
        txtViewDetails.setColumns(20);
        txtViewDetails.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        txtViewDetails.setRows(5);
        txtViewDetails.setToolTipText("");
        jScrollPane1.setViewportView(txtViewDetails);

        btnViewAllEmployee.setText("View All Employee");
        btnViewAllEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteEmployeePanelLayout = new javax.swing.GroupLayout(deleteEmployeePanel);
        deleteEmployeePanel.setLayout(deleteEmployeePanelLayout);
        deleteEmployeePanelLayout.setHorizontalGroup(
            deleteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEmployeePanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteEmployeePanelLayout.createSequentialGroup()
                .addGroup(deleteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deleteEmployeePanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDeleteEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deleteEmployeePanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(deleteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(deleteEmployeePanelLayout.createSequentialGroup()
                                .addComponent(btnDeleteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnViewAllEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteEmpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );
        deleteEmployeePanelLayout.setVerticalGroup(
            deleteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEmployeePanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(deleteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeleteEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(deleteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteEmpBack)
                    .addComponent(btnViewAllEmployee))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteEmpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpBackActionPerformed
        OptionsFrame  opFrame=new OptionsFrame();
        opFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeleteEmpBackActionPerformed

    private void btnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpActionPerformed
        try
        {
            String empNo = txtDeleteEmpNo.getText().trim();
            boolean result = empDAO.deleteEmployee(Integer.parseInt(empNo));
            if(result==true)
                JOptionPane.showMessageDialog(null, "Record Deleted successfully !", "Delete Record !", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(null, "Record not deleted successfully !", "Delete Record !", JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "DB Error !", "SQL Error !", JOptionPane.INFORMATION_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteEmpActionPerformed

    private void btnViewAllEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllEmployeeActionPerformed
        try
        {
            Connection con = DBConnection.getConnection();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select * from emp order by id");
            StringBuilder sb=new StringBuilder();
            sb.append("EmpID"+"\t"+"Emp Name"+"\t"+"Emp Age"+"\t"+"Emp Salary"+"\t"+"Emp Address"+"\n");
            System.out.println();
            txtViewDetails.setText("");
            while(rs.next())
            {
               
                int eno=rs.getInt(1);
                String ename=rs.getString(2);
                int eage=rs.getInt(3);
                double sal=rs.getDouble(4);
                String eadd=rs.getString(5);
                sb.append(eno+"\t"+ename+"\t"+eage+"\t"+sal+"\t"+eadd+"\n");
            }
            txtViewDetails.setText(sb.toString());
        }
        
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "DB Error!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnViewAllEmployeeActionPerformed

    private void txtDeleteEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteEmpNoActionPerformed
        try
        {
            Connection con = DBConnection.getConnection();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select * from emp order by id");
            StringBuilder sb=new StringBuilder();
            sb.append("EmpID"+"\t"+"Emp Name"+"\t"+"Emp Age"+"\t"+"Emp Salary"+"\t"+"Emp Address"+"\n");
            System.out.println();
            txtViewDetails.setText("");
            while(rs.next())
            {
               
                int eno=rs.getInt(1);
                String ename=rs.getString(2);
                int eage=rs.getInt(3);
                double sal=rs.getDouble(4);
                String eadd=rs.getString(5);
                sb.append(eno+"\t"+ename+"\t"+eage+"\t"+sal+"\t"+eadd+"\n");
            }
            txtViewDetails.setText(sb.toString());
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "DB Error !", "SQL Error !", JOptionPane.INFORMATION_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtDeleteEmpNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteEmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteEmp;
    private javax.swing.JButton btnDeleteEmpBack;
    private javax.swing.JButton btnViewAllEmployee;
    private javax.swing.JPanel deleteEmployeePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDeleteEmpNo;
    private javax.swing.JTextArea txtViewDetails;
    // End of variables declaration//GEN-END:variables
}
